<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.openhab.addons.bundles</groupId>
    <artifactId>org.openhab.addons.reactor.bundles</artifactId>
    <version>5.0.2-SNAPSHOT</version>
  </parent>

  <artifactId>org.openhab.binding.bom</artifactId>

  <name>openHAB Add-ons :: Bundles :: Bureau of Meteorology</name>

  <dependencies>
    <!--dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-core</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency>
      <dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-tiff</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency>
      <dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-psd</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency>
      <dependency>
      <groupId>com.twelvemonkeys.imageio</groupId>
      <artifactId>imageio-metadata</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency>
      <dependency>
      <groupId>com.twelvemonkeys.common</groupId>
      <artifactId>common-image</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency>
      <dependency>
      <groupId>com.twelvemonkeys.common</groupId>
      <artifactId>common-io</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency>
      <dependency>
      <groupId>com.twelvemonkeys.common</groupId>
      <artifactId>common-lang</artifactId>
      <version>3.4.2</version>
      <scope>compile</scope>
      </dependency -->
    <dependency>
      <groupId>commons-net</groupId>
      <artifactId>commons-net</artifactId>
      <version>3.11.1</version>
      <scope>provided</scope>
    </dependency>
    <!--<dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.17.0</version>
      <scope>provided</scope>
    </dependency>   -->
  </dependencies>

</project>
